# Site wide configuration

title: "aspnet5co"
description: "ASP.NET 5: Advocacy and collaboration"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://lopezpdvn.github.io/aspnet5co
baseurl: /aspnet5co

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: "Pedro I. Lopez"
  email: "m@lopezpedro.net"
  twitter: "lopezpdvn"
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
