# Site wide configuration

title: "ASP.NET5CO"
description: "ASP.NET 5: Advocacy and collaboration"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:

# Github Pages
url: //pedroivanlopez.com/aspnet5co
baseurl: /aspnet5co

# Development
#url: http://localhost:4000
#baseurl: /

# Jekyll configuration
urldoc: "http://pedroivanlopez.com/aspnet5co"

project_description: "[ASP.NET5CO](http://pedroivanlopez.com/aspnet5co) is a project that comprises the efforts by [Pedro Ivan Lopez](http://pedroivanlopez.com) to socially and technically advocate the [ASP.NET 5](http://www.asp.net/vnext) framework. [M.C. Aída Lucina González Lara](http://www.fime.uanl.mx/oferta_educativa/maestrias/ingenieria_de_la_informacion/) is the project advisor at [FIME](http://www.fime.uanl.mx/)/[UANL](http://www.uanl.mx/)."

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..6
highlighter: rouge
gems:
  - jekyll-sitemap

github_username: lopezpdvn


# Site owner
owner:
  name: "Pedro Ivan Lopez"
  email: "m@pedroivanlopez.com"
  twitter: "lopezpdvn"
  website: "http://pedroivanlopez.com"
  google:
    ad-client: 
    ad-slot: 
  bio: "Pedro Ivan Lopez is a software engineer interested in web and large scale systems."
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:

include: ["LICENSE.txt"]

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
